#!/bin/bash
# ============================================
# Network Configuration Script
# Auto Server Provisioning - farahamimah.net
# ============================================

GREEN='\033[0;32m'
RED='\033[0;31m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

INTERFACE=$(ip -o link show | awk -F': ' '{print $2}' | grep -v lo | head -1)

clear
echo -e "${CYAN}"
echo "=================================================="
echo "   NETWORK CONFIGURATION                         "
echo "   Auto Server Provisioning - farahamimah.net    "
echo "=================================================="
echo -e "${NC}"

echo -e "${YELLOW}Interface terdeteksi : $INTERFACE${NC}"
echo -e "${YELLOW}IP Saat Ini          : $(hostname -I | awk '{print $1}')${NC}"
echo ""
echo -e "Pilih jaringan yang digunakan:"
echo ""
echo -e "  ${GREEN}[1]${NC} WiFi Rumah  │ Debian: 192.168.1.43 │ Proxmox: 192.168.1.20"
echo -e "  ${GREEN}[2]${NC} WiFi LAB    │ Debian: 10.11.8.43   │ Proxmox: 10.11.8.20"
echo -e "  ${GREEN}[3]${NC} WiFi Kelas  │ Debian: 10.11.5.43   │ Proxmox: 10.11.5.20"
echo -e "  ${GREEN}[4]${NC} Kabel LAN   │ Debian: 10.3.2.43    │ Proxmox: 10.3.2.20"
echo -e "  ${GREEN}[5]${NC} Custom      │ Input manual"
echo -e "  ${GREEN}[6]${NC} DHCP        │ Otomatis"
echo -e "  ${RED}[0]${NC} Keluar"
echo ""
read -p "Masukkan pilihan [0-6]: " choice

set_static_ip() {
    local IP=$1
    local GATEWAY=$2
    local DNS=$3
    local NETMASK=$4
    local PROXMOX=$5
    local NETWORK_NAME=$6

    cat > /etc/network/interfaces << EOF
# Auto generated by network-config.sh
# Jaringan  : $NETWORK_NAME
# Tanggal   : $(date '+%Y-%m-%d %H:%M:%S')
# Auto Server Provisioning - farahamimah.net

source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback

auto $INTERFACE
iface $INTERFACE inet static
    address $IP
    netmask $NETMASK
    gateway $GATEWAY
    dns-nameservers $DNS 8.8.8.8
EOF

    # Restart network
    ifdown $INTERFACE 2>/dev/null
    ifup $INTERFACE 2>/dev/null
    sleep 2

    # Update /etc/hosts
    sed -i "/server.farahamimah.net/d" /etc/hosts
    sed -i "/proxmox.farahamimah.net/d" /etc/hosts
    echo "$IP     server.farahamimah.net server" >> /etc/hosts
    echo "$PROXMOX proxmox.farahamimah.net proxmox" >> /etc/hosts

    echo -e "${GREEN}[NET] Jaringan   : $NETWORK_NAME${NC}"
    echo -e "${GREEN}[NET] IP Debian  : $IP${NC}"
    echo -e "${GREEN}[NET] IP Proxmox : $PROXMOX${NC}"
    echo -e "${GREEN}[NET] Gateway    : $GATEWAY${NC}"
    echo -e "${GREEN}[NET] Netmask    : $NETMASK${NC}"
    echo -e "${GREEN}[NET] DNS        : $DNS & 8.8.8.8${NC}"
}

set_dhcp() {
    cat > /etc/network/interfaces << EOF
# Auto generated by network-config.sh
# Mode: DHCP
# Tanggal: $(date '+%Y-%m-%d %H:%M:%S')

source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback

auto $INTERFACE
iface $INTERFACE inet dhcp
EOF

    ifdown $INTERFACE 2>/dev/null
    ifup $INTERFACE 2>/dev/null
    sleep 3

    # Update /etc/hosts dengan IP baru
    IP_DHCP=$(hostname -I | awk '{print $1}')
    sed -i "/server.farahamimah.net/d" /etc/hosts
    echo "$IP_DHCP server.farahamimah.net server" >> /etc/hosts
    echo -e "${GREEN}[NET] DHCP aktif, IP: $IP_DHCP${NC}"
}

case $choice in
    1)
        echo -e "${YELLOW}[NET] Konfigurasi WiFi Rumah...${NC}"
        set_static_ip \
            "192.168.1.43" \
            "192.168.1.1" \
            "192.168.1.1" \
            "255.255.255.0" \
            "192.168.1.20" \
            "WiFi Rumah"
        ;;
    2)
        echo -e "${YELLOW}[NET] Konfigurasi WiFi LAB...${NC}"
        set_static_ip \
            "10.11.8.43" \
            "10.11.8.1" \
            "10.11.8.1" \
            "255.255.255.0" \
            "10.11.8.20" \
            "WiFi LAB"
        ;;
    3)
        echo -e "${YELLOW}[NET] Konfigurasi WiFi Kelas...${NC}"
        set_static_ip \
            "10.11.5.43" \
            "10.11.5.1" \
            "10.11.5.1" \
            "255.255.255.0" \
            "10.11.5.20" \
            "WiFi Kelas"
        ;;
    4)
        echo -e "${YELLOW}[NET] Konfigurasi Kabel LAN LAB...${NC}"
        set_static_ip \
            "10.3.2.43" \
            "10.3.2.1" \
            "10.3.2.1" \
            "255.255.255.0" \
            "10.3.2.20" \
            "Kabel LAN LAB"
        ;;
    5)
        echo -e "${YELLOW}[NET] Konfigurasi Custom...${NC}"
        read -p "Nama Jaringan       : " CUSTOM_NAME
        read -p "IP Debian           : " CUSTOM_IP
        read -p "Netmask             : " CUSTOM_MASK
        read -p "Gateway             : " CUSTOM_GW
        read -p "DNS Server          : " CUSTOM_DNS
        read -p "IP Proxmox          : " PROXMOX_IP
        set_static_ip \
            "$CUSTOM_IP" \
            "$CUSTOM_GW" \
            "$CUSTOM_DNS" \
            "$CUSTOM_MASK" \
            "$PROXMOX_IP" \
            "$CUSTOM_NAME"
        ;;
    6)
        echo -e "${YELLOW}[NET] Konfigurasi DHCP...${NC}"
        set_dhcp
        PROXMOX_IP="(cek manual)"
        ;;
    0)
        echo -e "${RED}Keluar...${NC}"
        exit 0
        ;;
    *)
        echo -e "${RED}[NET] Pilihan tidak valid!${NC}"
        exit 1
        ;;
esac

# Tampilkan hasil akhir
sleep 2
IP_NOW=$(hostname -I | awk '{print $1}')
echo ""
echo -e "${CYAN}================================================${NC}"
echo -e "${GREEN} ✅ Konfigurasi Jaringan Selesai!${NC}"
echo -e "${CYAN}------------------------------------------------${NC}"
echo -e "${YELLOW} Info Server:${NC}"
echo -e "  IP Debian   : ${GREEN}$IP_NOW${NC}"
echo -e "  IP Proxmox  : ${GREEN}$PROXMOX_IP${NC}"
echo -e "  Hostname    : ${GREEN}$(hostname)${NC}"
echo -e "  Domain      : ${GREEN}server.farahamimah.net${NC}"
echo -e "${CYAN}------------------------------------------------${NC}"
echo -e "${YELLOW} Akses Layanan:${NC}"
echo -e "  🌐 Web       : http://$IP_NOW"
echo -e "  🗄️  phpMyAdmin: http://$IP_NOW/phpmyadmin"
echo -e "  🔒 SSH       : ssh farah@$IP_NOW"
echo -e "  📊 Proxmox   : https://$PROXMOX_IP:8006"
echo -e "${CYAN}================================================${NC}"
