#!/bin/bash
# ============================================
# Network Watchdog - Auto Change IP
# Auto Server Provisioning - farahamimah.net
# Berjalan otomatis via crontab setiap menit
# ============================================

# ============================================
# KONFIGURASI — SESUAIKAN DI SINI
# ============================================
HOST_NUMBER=43        # Angka belakang IP server kamu
PROXMOX_HOST=20       # Angka belakang IP Proxmox kamu
INTERFACE="ens18"     # Nama interface jaringan
# ============================================

LOG="/var/log/auto-server-provisioning/watchdog.log"
LAST_NETWORK_FILE="/tmp/last_network"

# Buat folder log jika belum ada
mkdir -p /var/log/auto-server-provisioning

# ============================================
# STEP 1 - Dapatkan gateway saat ini
# ============================================
CURRENT_GW=$(ip route | grep default | awk '{print $3}' | head -1)

# Jika tidak ada gateway, skip
if [ -z "$CURRENT_GW" ]; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') | Tidak ada gateway, skip." >> $LOG
    exit 0
fi

# Ambil 3 oktet pertama dari gateway
NETWORK_PREFIX=$(echo $CURRENT_GW | cut -d'.' -f1-3)
TARGET_IP="$NETWORK_PREFIX.$HOST_NUMBER"
PROXMOX_IP="$NETWORK_PREFIX.$PROXMOX_HOST"

# ============================================
# STEP 2 - Cek apakah jaringan berubah
# ============================================
CURRENT_IP=$(hostname -I | awk '{print $1}')
CURRENT_PREFIX=$(echo $CURRENT_IP | cut -d'.' -f1-3)

# Baca jaringan terakhir dari file
LAST_NETWORK=""
if [ -f "$LAST_NETWORK_FILE" ]; then
    LAST_NETWORK=$(cat $LAST_NETWORK_FILE)
fi

# Jika jaringan sama dengan sebelumnya, tidak perlu ganti
if [ "$NETWORK_PREFIX" = "$LAST_NETWORK" ]; then
    exit 0
fi

# ============================================
# STEP 3 - Jaringan berubah! Ganti IP
# ============================================
echo "$(date '+%Y-%m-%d %H:%M:%S') | ================================" >> $LOG
echo "$(date '+%Y-%m-%d %H:%M:%S') | Jaringan berubah terdeteksi!" >> $LOG
echo "$(date '+%Y-%m-%d %H:%M:%S') | Network lama : $LAST_NETWORK.0/24" >> $LOG
echo "$(date '+%Y-%m-%d %H:%M:%S') | Network baru : $NETWORK_PREFIX.0/24" >> $LOG
echo "$(date '+%Y-%m-%d %H:%M:%S') | IP lama      : $CURRENT_IP" >> $LOG
echo "$(date '+%Y-%m-%d %H:%M:%S') | IP baru      : $TARGET_IP" >> $LOG
echo "$(date '+%Y-%m-%d %H:%M:%S') | Gateway      : $CURRENT_GW" >> $LOG
echo "$(date '+%Y-%m-%d %H:%M:%S') | Proxmox      : $PROXMOX_IP" >> $LOG

# ============================================
# STEP 4 - Tulis konfigurasi network baru
# ============================================
cat > /etc/network/interfaces << INTERFACES
# ============================================
# Auto generated by network-watchdog.sh
# Tanggal : $(date '+%Y-%m-%d %H:%M:%S')
# Network : $NETWORK_PREFIX.0/24
# Gateway : $CURRENT_GW
# ============================================

source /etc/network/interfaces.d/*

auto lo
iface lo inet loopback

auto $INTERFACE
iface $INTERFACE inet static
    address $TARGET_IP
    netmask 255.255.255.0
    gateway $CURRENT_GW
    dns-nameservers $CURRENT_GW 8.8.8.8
INTERFACES

# ============================================
# STEP 5 - Terapkan IP baru
# ============================================
ifdown $INTERFACE 2>/dev/null
sleep 1
ifup $INTERFACE 2>/dev/null
sleep 3

# ============================================
# STEP 6 - Update /etc/hosts
# ============================================
sed -i "/server.farahamimah.net/d" /etc/hosts
sed -i "/proxmox.farahamimah.net/d" /etc/hosts
echo "$TARGET_IP   server.farahamimah.net server" >> /etc/hosts
echo "$PROXMOX_IP  proxmox.farahamimah.net proxmox" >> /etc/hosts

# ============================================
# STEP 7 - Simpan jaringan saat ini
# ============================================
echo "$NETWORK_PREFIX" > $LAST_NETWORK_FILE

# ============================================
# STEP 8 - Log hasil
# ============================================
NEW_IP=$(hostname -I | awk '{print $1}')
echo "$(date '+%Y-%m-%d %H:%M:%S') | IP sekarang  : $NEW_IP" >> $LOG
echo "$(date '+%Y-%m-%d %H:%M:%S') | ✅ Selesai!" >> $LOG
echo "$(date '+%Y-%m-%d %H:%M:%S') | ================================" >> $LOG
